<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="TTS-SCRIT-5" ignored="0" name="UploadSingleResume with EmailID and mobile number(.Docx) and NegativeResume for above 3mb" tests="3" failures="1" timestamp="09 Jun 2023 05:57:39 GMT" time="111.738" errors="0">
  <testcase name="login" time="75.176" classname="com.Screenit.version3.Test.UploadIdResumeTestForPostiveAndNegativeflow">
    <failure type="java.lang.AssertionError" message="expected [https://test.screenit.io/#/dashboard_v3] but found [https://demo.screenit.io/#/dashboard_v3]">
      <![CDATA[java.lang.AssertionError: expected [https://test.screenit.io/#/dashboard_v3] but found [https://demo.screenit.io/#/dashboard_v3]at com.Screenit.version3.Pages.LoginPage.VerifyNavigateToTheDashBoard(LoginPage.java:64)at com.Screenit.version3.Test.UploadIdResumeTestForPostiveAndNegativeflow.login(UploadIdResumeTestForPostiveAndNegativeflow.java:57)... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- login -->
  <testcase name="UploadSingleResumeWithPostive" time="15.598" classname="com.Screenit.version3.Test.UploadIdResumeTestForPostiveAndNegativeflow"/>
  <testcase name="UploadSingleResumeWithNegative" time="16.952" classname="com.Screenit.version3.Test.UploadIdResumeTestForPostiveAndNegativeflow"/>
</testsuite> <!-- UploadSingleResume with EmailID and mobile number(.Docx) and NegativeResume for above 3mb -->
