<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="TTS-SCRIT-5" name="com.Screenit.version3.Test.SelectedOrRejectFlowForIAAS" tests="6" failures="1" timestamp="08 Jun 2023 12:16:21 GMT" time="763.528" errors="0">
  <testcase name="loginFunctionality" time="74.779" classname="com.Screenit.version3.Test.SelectedOrRejectFlowForIAAS">
    <failure type="java.lang.AssertionError" message="expected [https://test.screenit.io/#/dashboard_v3] but found [https://demo.screenit.io/#/dashboard_v3]">
      <![CDATA[java.lang.AssertionError: expected [https://test.screenit.io/#/dashboard_v3] but found [https://demo.screenit.io/#/dashboard_v3]at org.testng.Assert.fail(Assert.java:96)at org.testng.Assert.failNotEquals(Assert.java:776)at org.testng.Assert.assertEqualsImpl(Assert.java:137)at org.testng.Assert.assertEquals(Assert.java:118)at org.testng.Assert.assertEquals(Assert.java:453)at org.testng.Assert.assertEquals(Assert.java:463)at com.Screenit.version3.Pages.LoginPage.VerifyNavigateToTheDashBoard(LoginPage.java:64)at com.Screenit.version3.Test.SelectedOrRejectFlowForIAAS.loginFunctionality(SelectedOrRejectFlowForIAAS.java:53)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)at java.lang.reflect.Method.invoke(Unknown Source)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
    </failure>
  </testcase> <!-- loginFunctionality -->
  <testcase name="UploadIdFile" time="16.117" classname="com.Screenit.version3.Test.SelectedOrRejectFlowForIAAS"/>
  <testcase name="CreateInterviewerDescriptionIDwithclickPostButtonAndFilledTheMandatoryField" time="144.194" classname="com.Screenit.version3.Test.SelectedOrRejectFlowForIAAS"/>
  <testcase name="UploadSingleResumeWithPostive" time="16.207" classname="com.Screenit.version3.Test.SelectedOrRejectFlowForIAAS"/>
  <testcase name="SelectSetavailability" time="148.109" classname="com.Screenit.version3.Test.SelectedOrRejectFlowForIAAS"/>
  <testcase name="JavaDeveloperPostStatus" time="364.122" classname="com.Screenit.version3.Test.SelectedOrRejectFlowForIAAS"/>
</testsuite> <!-- com.Screenit.version3.Test.SelectedOrRejectFlowForIAAS -->
