<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="TTS-SCRIT-5" name="com.Screenit.version3.Test.LoginTestForPostiveAndNegativeFlow" tests="2" failures="0" timestamp="11 Jul 2023 07:31:55 GMT" time="84.754" errors="1">
  <testcase name="endTest" time="6.090" classname="com.Screenit.version3.Test.LoginTestForPostiveAndNegativeFlow">
    <error type="org.apache.commons.mail.EmailException" message="Sending the email to the following server failed : smtp.gmail.com:465">
      <![CDATA[org.apache.commons.mail.EmailException: Sending the email to the following server failed : smtp.gmail.com:465at org.apache.commons.mail.Email.sendMimeMessage(Email.java:1469)at org.apache.commons.mail.Email.send(Email.java:1496)at com.Screenit.version3.Initializer.Initializer.email(Initializer.java:145)at com.Screenit.version3.Test.LoginTestForPostiveAndNegativeFlow.endTest(LoginTestForPostiveAndNegativeFlow.java:141)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)at java.lang.reflect.Method.invoke(Unknown Source)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:451)at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)at org.testng.internal.TestMethodWorker.invokeAfterClassMethods(TestMethodWorker.java:208)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)Caused by: javax.mail.AuthenticationFailedException: 535-5.7.8 Username and Password not accepted. Learn more at535 5.7.8  https://support.google.com/mail/?p=BadCredentials y11-20020a637d0b000000b0055b149a6db5sm907202pgc.43 - gsmtpat com.sun.mail.smtp.SMTPTransport$Authenticator.authenticate(SMTPTransport.java:932)at com.sun.mail.smtp.SMTPTransport.authenticate(SMTPTransport.java:843)at com.sun.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:748)at javax.mail.Service.connect(Service.java:388)at javax.mail.Service.connect(Service.java:246)at javax.mail.Service.connect(Service.java:195)at javax.mail.Transport.send0(Transport.java:254)at javax.mail.Transport.send(Transport.java:124)at org.apache.commons.mail.Email.sendMimeMessage(Email.java:1459)... 29 more]]>
    </error>
  </testcase> <!-- endTest -->
  <testcase name="loginFunctionality" time="78.664" classname="com.Screenit.version3.Test.LoginTestForPostiveAndNegativeFlow"/>
</testsuite> <!-- com.Screenit.version3.Test.LoginTestForPostiveAndNegativeFlow -->
