<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="TTS-SCRIT-5" ignored="0" name="forgot password with new mailid" tests="1" failures="1" timestamp="09 Jun 2023 05:37:53 GMT" time="67.924" errors="0">
  <testcase name="forgetPassword" time="64.507" classname="com.Screenit.version3.Test.ForgotPasswordTestForPostiveAndNegativeFlow">
    <failure type="java.lang.AssertionError" message="expected [https://test.screenit.io/#/forget_v3/password] but found [https://demo.screenit.io/#/forget_v3/password]">
      <![CDATA[java.lang.AssertionError: expected [https://test.screenit.io/#/forget_v3/password] but found [https://demo.screenit.io/#/forget_v3/password]at com.Screenit.version3.Pages.ForgotPasswordPage.getUrlForForgotPassword(ForgotPasswordPage.java:64)at com.Screenit.version3.Test.ForgotPasswordTestForPostiveAndNegativeFlow.forgetPassword(ForgotPasswordTestForPostiveAndNegativeFlow.java:52)... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- forgetPassword -->
</testsuite> <!-- forgot password with new mailid -->
